site_name: Xiaomi

theme:
  name: material
  palette:
    primary: blue
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  nav:
  - Главная: index.md
  - Руководство: guide.md
  - FAQ: faq.md
  - Rsdf: 00.md
